# Generated by Django 4.2.2 on 2023-06-09 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('example_app.custom_blogpost', 'Can change the status of tasks')]},
        ),
    ]
