# Generated by Django 4.2.2 on 2023-06-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('custom_blogpost', 'can view custom')]},
        ),
    ]
